## 자료를 보면서 공부할 노트

# 배열

In [1]:
import numpy as np

In [24]:
arr = np.arange(10)
# (0:5)같은거 안먹힘
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int32


In [16]:
k = ([[10,20,30,40],[50,60,70,80]])
k
## np.array()  안에 배열

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [23]:
"""
ndim : 배열의 차원
shape : 배열의 크기(첫번째 리스트)
size : 배열 제일 안쪽 요소 수

"""
print(k.ndim,
k.shape,
k.size,
k.dtype
)


2 (2, 4) 8 int32


In [25]:
a = np.array([1,2,3,4,5])
print(
    a[2],
    a[-1],
)

3 5


In [30]:
b = np.array([[1,2,3],[4,5,6]])
print(
    b[0,1],
    b[-1,-1],
    b.shape 
)

2 6 (2, 3)


In [31]:
c = np.array([[0,1,2,3,4],
              [5,6,7,8,9]])
c
print(
    c[0, :],
    c[1, 1:],
    c[:2, :2]
)

[0 1 2 3 4] [6 7 8 9] [[0 1]
 [5 6]]


In [32]:
m = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]])

#1. 이 행렬에서 값 7 을 인덱싱한다.
print(m[1,2])
#2. 이 행렬에서 값 14 을 인덱싱한다.
print(m[-1,-1])
#3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
print(m[1,1:3])
#4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
print(m[1:,2])
#5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
print(m[:2,3:])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


In [42]:
"""배열 크기 변환"""
a = np.arange(12)
b = a.reshape(3,4)   # 4개씩 3개
print("(3,4)\n",b)
b = a.reshape(4, -1)   # -1 ==> 자동으로 채움
print("(4,-1)\n",b)
b = a.reshape(2,-1,2)
print("(2,-1,2)\n",b)    # 2개씩 묶고 두개로 또 분리
b = a.flatten()
print(".flatten() : ",b)   # 1차원으로 반환하는 복사본 ravel은 원본

(3,4)
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(4,-1)
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(2,-1,2)
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
.flatten() :  [ 0  1  2  3  4  5  6  7  8  9 10 11]


# 차원 축소 연산

In [43]:
x = np.array([1,2,3,4,5,6])
# 총합
z = np.sum(x)
print("np.sum()",z)
i = x.sum()
print(".sum()",i)
j = np.min(x)
print("np.min(x)",j)

"""
np.sum()이 귀찮아도 처리 시간이 월등히 빠르다.
all은 모두 참일 경우, any는 하나라도 참일 경우
"""


np.sum() 21
.sum() 21
np.min(x) 1


## Pandas

# 패키지 불러오기 & 시리즈 클래스(Series Class)

In [12]:
import pandas as pd
import numpy as np

# 넘파이로 배열 생성하기
arr = np.array([1,2,3,4,5])
arr[0]
# 팬더스로 시리즈 생성하기
obj = pd.Series([4,2,-6,0])
print(obj)
print(obj.values) #값 불러오기
print(obj.index)  #(인덱스의 시작값, 끝 값, 단계)
print(obj.dtype)  #요소들의 타입

# 인덱스 설정
obj1 = pd.Series([4,2,-6,1], index=["a","b","c","d"])   # , 인덱스 = 배열

print(obj1)

0    4
1    2
2   -6
3    0
dtype: int64
[ 4  2 -6  0]
RangeIndex(start=0, stop=4, step=1)
int64
a    4
b    2
c   -6
d    1
dtype: int64


In [22]:
obj1 = pd.Series([1024,5234,6224,1141], index=["서울", "구미", "대구", "부산"])

# 시리즈에서 값 불러오기 = 객체[인덱스]   여러개 불러오는 경우 리스트로 불러옴
print(obj1[1], obj1["대구"])
print(obj1[["서울","대구","부산"]])
print(obj1[[0,3,1]])

5234 6224
서울    1024
구미    5234
대구    6224
부산    1141
dtype: int64
서울    1024
부산    1141
구미    5234
dtype: int64


C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_26692\536662471.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(obj1[1], obj1["대구"])
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_26692\536662471.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(obj1[[0,3,1]])


# 시리즈 슬라이싱 & 수정,삭제

In [24]:
# 슬라이싱 할 경우엔 따로 리스트를 만들지 않고 바로 선언
#  입력과 삭제도 인덱스만 입력

print(obj1[0:2])
print(obj1["구미":"부산"])

# 입력
obj1["구미"] = 1234
print(obj1)

del obj1["구미"]
obj1

서울    1024
구미    1234
dtype: int64
구미    1234
대구    6224
부산    1141
dtype: int64
서울    1024
구미    1234
대구    6224
부산    1141
dtype: int64


서울    1024
대구    6224
부산    1141
dtype: int64

In [26]:
obj2 = {"Kim": 35000,
        "Park": 67000,
        "Joon": 12000,
        "Choi": 4000}

obj2 = pd.Series(obj2)
print(obj2)

obj2.name = "People"
obj2.index.name = "Full Names"
obj2

Kim     35000
Park    67000
Joon    12000
Choi     4000
dtype: int64


Full Names
Kim     35000
Park    67000
Joon    12000
Choi     4000
Name: People, dtype: int64

# 데이터 프레임